
package TelasPI;

import classespi.CadClien;
import classespi.InfoCliente;
 
import classespi.PI;
import javax.swing.JOptionPane;


public class telaCadCliente extends javax.swing.JFrame {
    InfoCliente cliente = new InfoCliente();
    
    public telaCadCliente() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        botaocadastrar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 40));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 30));

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 30));

        botaocadastrar.setText("CADASTRAR");
        botaocadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaocadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaCadClient.png"))); // NOI18N
        background.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                backgroundAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void backgroundAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_backgroundAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundAncestorAdded

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
       
    }//GEN-LAST:event_nomeActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void botaocadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocadastrarActionPerformed
        PI co = new PI();
        CadClien funcao = new CadClien();
        boolean conec = true;
        int resposta;
        
        
        cliente.setNome(nome.getText());
        cliente.setEmail(email.getText());
        cliente.setSenha(senha.getText());
     
        if(nome.getText().trim().isEmpty()||email.getText().trim().isEmpty() || senha.getText().trim().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Preencha todos os campos ");
            return;
        }else{
           
        co.getConnection();
        if(conec == false){
                JOptionPane.showMessageDialog(null, "erro de conexão");
            }else{
                resposta = funcao.CADASTRAR(cliente);
                if (resposta == 1){
                    JOptionPane.showMessageDialog(null, "Cliente foi cadastrado");
                }
        
        }
    }//GEN-LAST:event_botaocadastrarActionPerformed
    }
        
        
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadCliente().setVisible(true);
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton botaocadastrar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField senha;
    // End of variables declaration//GEN-END:variables
}
